load("@rules_cc//cc:defs.bzl", "cc_library")
package(default_visibility = ["//visibility:public"])

cc_library(
    name = "resnet_calculators",
    deps = [
        "//resnet-mediapipe/graphs/subgraphs:resnet_subgraph",
    ],
)
